##################### RODANDO O PACOTE AmostraBrasil #################################

########## OBJETIVO:
# AUXILIAR PESQUISADORES QUE NAO CONHECEM O R A RODAR O PACOTE 
##"AmostraBrasil", DOS PROFESSORES RICARDO CORDEIRO, 
## CELSO STEPHAN E MARIA RITA DONALISIO.

########## PARA QUE SERVE O PACOTE "AmostraBrasil"?
# O PACOTE "AmostraBrasil" INSTRUMENTALIZA O PESQUISADOR A 
##AUTOMATIZAR "...a obtencao de amostras aleatorias - simples,
##sistematicas e estratificadas - de domicilios de quaisquer 
##municipios do Brasil".

#A DIVULGACAO ELABORADA PELOS AUTORES PODE SER ACESSADA EM:
##http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2016001106002
## RECOMENDO MUITO A LEITURA!

#######################################################################################
########################## INFORMACOES IMPORTANTES ####################################
# SE VOCE JA CONHECE O R E ESTA LENDO ESSE SCRIPT NO RSTUDIO, 
##PULE PARA A LINHA 61.

# ESSE SCRIPT TOMAM COMO PRESSUPOSTO QUE VOCE JA TEM O R INSTALADO
# E ESTA UTILIZANDO O R STUDIO.
# SE AINDA NAO BAIXOU ESSES PROGRAMAS, SIGA OS PASSOS:
# 1- BAIXE ESSE SCRIPT, QUE VOCE ESTA LENDO AGORA, EM UMA PASTA
##DE SEU COMPUTADOR.

# 2- ACESSE O SITE: https://www.r-project.org/
# BAIXE E INSTALE A VERSAO MAIS RECENTE DO R.

# 3- ACESSE O SITE: https://www.rstudio.com/products/rstudio/download/
# BAIXE E INSTALE A VERSAO MAIS RECENTE DO R STUDIO.

# 4- ABRA O RSTUDIO NO SEU COMPUTADOR.

# 5- NO R STUDIO, CLIQUE EM File/Open File...

# 6- LOCALIZE ESSE SCRIPT "RODANDO_AmostraBrasil.R"

# 7- ABRA O ARQUIVO E SIGA PARA A LINHA 54 DESSE SCRIPT.

# O SIMBOLO # E UTILIZADO PARA INSERIR UMA INFORMACAO/LEMBRETE PARA
##OS LEITORES HUMANOS.
# TUDO O QUE VEM APOS ESSE SIMBOLO, E DESCONSIDERADO PELO PROGRAMA.

# COMANDOS SAO TODAS AS LINHAS QUE NAO SAO PRECEDIDOS POR
##ESSE SIMBOLO (#) E SEM ESPACO NO INICIO.

#PARA RODAR OS COMANDOS, COLOQUE O CURSOR EM QUALQUER POSICAO
##DE SUA LINHA E PRESSIONE OS BOTOES CRTL + ENTER.
# EXEMPLO:

paste("OLA, TUDO BEM?") #PRESSIONE CTRL + ENTER NESSA LINHA.

#O COMANDO EXECUTADO SERA EXIBIDO NA TELA ABAIXO (CONSOLE)     
# E AQUI O CURSOR PULA PARA A PROXIMA LINHA. 

#ENFIM, VAMOS AO TRABALHO!

########## PASSO 01 #######
# BUSCAR O CODIGO MUNICIPIO DE REFERENCIA NA BASE DO IBGE:
# COPIAR E COLAR O LINK ABAIXO (SEM O #), COLAR E BUSCAR NO SEU 
##NAVEGADOR DE INTERNET. 
# https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/15761-areas-dos-municipios.html?t=acesso-ao-produto&c=
# BUSCAR O CODIGO DO MUNICIPIO NA CAIXA DE SELECAO 
##"Selecione um nivel geografico"

# COPIE E COLE O CODIGO NUMERICO DO MUNICIPIO NA LINHA ABAIXO:

##CODIGO MUNICIPIO => 3536505 (ESSE E UM EXEMPLO, APAGUE ESSE NUMERO E 

#COLOQUE O SEU CODIGO NO LUGAR).
# USAREMOS ESSE CODIGO MAIS TARDE

########## PASSO 02 #######
# INSTALAR OS PACOTES ABAIXO.
# PARA ISSO, COLOCAR O CURSOR NA LINHA DO COMANDO E PRESSIONAR 
##CRTL + ENTER.VOCE VERA NA TELA ABAIXO, CONSOLE, QUE O PROGRAMA 
##IRA RODAR O COMANDO. 
# O COMANDO ESTARA FINALIZADO QUANDO APARECER NO CONSOLE
##O SINALIZADOR DE LINHA, > ,DO LADO ESQUERDO DA TELA.

install.packages("tidyverse")
install.packages("writexl")
install.packages("AmostraBrasil")
#DICA: VOCE SO PRECISA INSTALAR OS PACOTES UMA VEZ.
## NAS PROXIMAS VEZES VOCE SO PRECISA CARREGAR OS PACOTES (PASSO 03).

########## PASSO 03 #######
#CARREGAR OS PACOTES INSTALADOS (CTRL + ENTER):
library(tidyverse)
library(writexl)
library(AmostraBrasil)

########## PASSO 04 #######
# RODAR O PACOTE AMOSTRA E GRAVAR SUA AMOSTRA.

# NA PROXIMA LINHA DE COMANDO VOCE VERA O SEGUINTE:
# minha.amostra <- amostraBrasil(codibge= "CODIGO_MUNICIPIO", N="tamanho da amostra")
# SUBSTITUA: 
# "CODIGO_MUNICIPIO" pelo codigo do Municipio que voce copiou da 
#pagina do IBGE e colou na linha 71 desse script.
#e "tamanho da amostra" pelo tamanho da sua amostra. EXEMPLO: 45

#EXEMPLO:
# minha.amostra <- amostraBrasil(codibge= "CODIGO_MUNICIPIO", N="tamanho da amostra")
#FICARA:
# minha.amostra <- amostraBrasil(codibge= 3536505, N=45)

minha.amostra <- amostraBrasil(codibge= "CODIGO_MUNICIPIO", N="tamanho da amostra")

#RODE O COMANDO ABAIXO, ELE IRA GRAVAR A SUA AMOSTRA:
minha.amostra%>% 
  separate(endIBGE, into = c("RUA", "NUMERO_CEP", "CIDADE_ESTADO", "PAIS"), ", " ) %>% 
  separate(NUMERO_CEP, into = c("NUMERO", "CEP"), " ") %>% 
  unite("ENDERECO", RUA, NUMERO, sep = ",") %>% 
  mutate(VISITADO = "NAO") %>%    
  write_xlsx ("MINHA_AMOSTRA.xlsx")

#PRONTO! SUA AMOSTRA FOI CONCLUIDA. ESTA SALVA NO SEU COMPUTADOR
#E SE CHAMA "MINHA_AMOSTRA.CSV".
#VOCE PODERA ABRI-LO EM SEU LEITOR DE PLANILHAS PREFERIDO.

#PARA ENCONTRAR O ARQUIVO EM SEU COMPUTADOR, 
##RODE O COMANDO ABAIXO. ELE IRA MOSTRAR O ENDERECO ONDE O ARQUIVO
#FOI SALVO.

getwd() #RESPONDE O DIRETORIO ONDE O ARQUIVO FOI SALVO NO SEU PC.

############DICAS FINAIS:
# LEIA O ARTIGO SUGERIDO NO INICIO PARA APLICACOES MAIS AVANCADAS.
# SE VOCE QUISER GEORREFERENCIAR, SUGIRO UTILIZAR O GOOGLE MAPS.
#PARA BAIXAR OS POLIGONOS DOS MUNICIPIOS E OUTROS ELEMENTOS 
##CARTOGRAFICOS BRASILEIROS ACESSE:
# http://www.gmapas.com/poligonos-ibge

# SCRIPT CRIADO POR JEFFERSON RODRIGUES, PARA AUXILIAR OS 
##PESQUISADORES QUE AINDA NAO  ESTAO HABITUADOS A UTILIZAR O R 
##A CONSTRUIREM SUAS AMOSTRAS ALEATORIAS.
# SE ESSE SCRIPT TE AJUDOU OU VOCE QUER AJUDAR A  MELHORA-LO,
## ACESSE, COMENTE, EDITE EM:

# https://github.com/JRodrigues27/Rodando-o-AmostraBrasil
